openapi: 3.0.0
info: 
  title: Box API
  version: 1.0.0
host: "TODO"
schemes: [ "http" ]
paths: 
  /getAuthToken: 
    get: 
      summary: Returns authentication token for a given email
      operationId: getAuthToken
      parameters: 
      - in: body
        required: true
        description: "Payload describing which email to get authentication token for."
        schema:
          type: body
          properties:
            name:
              type: string
            password:
              type: string
      
      responses: 
        '200':
          description: Authentication token to be used to validate at the /authenticate endpoint
          content:
            application/json:
              schema:
                properties:
                  auth_token: 
                    type: string
        '403':
          description: Permission Denied, not a valid email/password combination

  /authenticate:
    get:
      summary: Authenticates the user so that they can hit other endpoints (authentication expires after 1 hours)
      operationId: authenticate
      parameters:
        - name: Authentication
          in: header
          required: true
          description: Authentication token from /getAuthToken
          schema:
            type: string
      responses:
        '200':
          description: Successful authentication
        '400':
          description: Invalid token

  /order/createOrder: 
    get: 
      summary: Creates an order 
      operationId: createOrder
      parameters: 
        - name: Authentication
          in: header
          required: true
          description: Authentication token from /getAuthToken
          schema:
            properties:
              origin:
                type: string
      responses: 
        '200':
          description: Creates an order on the receiving box 
            and an order on the sending box. 
            If the reciever or sending box is empty that is assumed to be a human sender/receiver
          content:
            application/json:
              schema:
                properties:
                  auth_code: 
                    type: string
                  sender:
                    type: string
                  recipient:
                    type: string
                  status:
                    type: string
                    enum: ["ready","sending","sent","in_transit","receiving","received","stored"]
                  


 
